# Generated by Django 3.1.2 on 2020-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
